### ISSUE TITLE
which version used for numba 

### ISSUE THREAD

**Issue by JayeshGridScape** [xiaoyu258/DocProj#19]
we face issue in executing: resampling.py 
my numba lib version is 0.51.2
OS: Windows 10
Python 3.7

Error :
Traceback (most recent call last):
  File "resampling.py", line 203, in <module>
    resImg, resMsk = rectification(distortedImg, flow)
  File "resampling.py", line 194, in rectification
    iterSearch[blockspergrid, threadsperblock](padu, padv, paddistorted, resultImg, maxIter, precision, resultMsk)
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\compiler.py", line 770, in __call__
    self.stream, self.sharedmem)
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\compiler.py", line 861, in call
    kernel = self.compile(argtypes)
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\compiler.py", line 935, in compile
    kernel.bind()
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\compiler.py", line 576, in bind
    self._func.get()
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\compiler.py", line 446, in get
    ptx = self.ptx.get()
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\compiler.py", line 414, in get
    arch = nvvm.get_arch_option(*cc)
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 345, in get_arch_option
    return 'compute_%d%d' % arch
TypeError: not enough arguments for format string

Looks to me this might be a version mismatch issue 
can someone help with which version we need to use in the window and Linux?
Batter if provided all prerequisite lib name and version that needed that might help.

**Comment by xiaoyu258** [comment]
Here is the version of mine.
numba 0.40.0
numpy 1.19.1
scikit-image 0.17.2

**Comment by JayeshGridScape** [comment]
@xiaoyu258 on which OS .. Window or Linux batter if you provide a version

**Comment by xiaoyu258** [comment]
Windows 10 on my PC

**Comment by JayeshGridScape** [comment]
thanks
